name: DeployTrigger CI

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet publish -o publish
      working-directory: ./src/DeployTrigger
    - name: Create zip
      run: |
        mkdir DeployTrigger-linux-amd64
        mv src/DeployTrigger/publish/* DeployTrigger-linux-amd64/
        zip -r DeployTrigger-linux-amd64.zip DeployTrigger-linux-amd64
        mkdir dist
        mv DeployTrigger-linux-amd64 dist/
    - name: Upload binaries to pipeline artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DeployTrigger-linux-amd64
        path: ./dist
        retention-days: 30
    - name: Upload binaries to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./DeployTrigger-linux-amd64.zip
        asset_name: DeployTrigger-linux-amd64.zip
        tag: ${{ github.ref }}
        overwrite: true
